# Generated by Django 3.0.5 on 2020-04-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamkey',
            name='name',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
