# Generated by Django 3.0.5 on 2020-04-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0003_remove_streamkey_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='streamkey',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='streamkey',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
