# Generated by Django 3.0.5 on 2020-04-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0002_streamkey_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamkey',
            name='owner',
        ),
    ]
