# Generated by Django 3.0.5 on 2020-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0002_auto_20200426_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
