# Generated by Django 3.0.5 on 2020-04-26 19:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0003_auto_20200426_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='claimed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concierge.Identity'),
        ),
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
