# Generated by Django 3.0.5 on 2020-04-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='publish_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
