# Generated by Django 3.0.5 on 2020-04-26 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rtmp', '0002_stream_publish_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
