# Generated by Django 3.0.5 on 2020-05-01 13:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rtmp', '0003_auto_20200426_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'application_verbose_name', 'verbose_name_plural': 'application_verbose_name_plural'},
        ),
        migrations.AlterField(
            model_name='stream',
            name='application',
            field=models.ForeignKey(help_text='stream_application_help', on_delete=django.db.models.deletion.CASCADE, to='rtmp.Application'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(help_text='stream_name_help', max_length=100),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream',
            field=models.UUIDField(default=uuid.uuid4, help_text='stream_stream_help', unique=True),
        ),
    ]
