# Generated by Django 3.0.6 on 2020-05-31 09:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rtmp', '0004_auto_20200501_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'RTMP application', 'verbose_name_plural': 'RTMP applications'},
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(help_text='RTMP application name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='application',
            field=models.ForeignKey(help_text='Application which the stream is assigned to', on_delete=django.db.models.deletion.CASCADE, to='rtmp.Application'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(help_text='Name for this stream', max_length=100),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream',
            field=models.UUIDField(default=uuid.uuid4, help_text='Stream ID for this stream', unique=True),
        ),
    ]
