# Generated by Django 3.0.5 on 2020-04-23 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rtmp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestreamConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtmp.Stream')),
            ],
        ),
    ]
