# Generated by Django 3.0.5 on 2020-05-01 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtmp', '0004_auto_20200501_1302'),
        ('restream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restreamconfig',
            options={'verbose_name': 'restreamconfig_verbose_name', 'verbose_name_plural': 'restreamconfig_verbose_name_plural'},
        ),
        migrations.AlterField(
            model_name='restreamconfig',
            name='active',
            field=models.BooleanField(help_text='restreamconfig_activate_help'),
        ),
        migrations.AlterField(
            model_name='restreamconfig',
            name='name',
            field=models.CharField(help_text='restreamconfig_name_help', max_length=100),
        ),
        migrations.AlterField(
            model_name='restreamconfig',
            name='stream',
            field=models.ForeignKey(help_text='restreamconfig_stream_help', on_delete=django.db.models.deletion.CASCADE, to='rtmp.Stream'),
        ),
        migrations.AlterField(
            model_name='restreamconfig',
            name='target',
            field=models.CharField(help_text='restreamconfig_target_help', max_length=500),
        ),
    ]
