# Generated by Django 3.1.13 on 2021-12-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restream', '0002_auto_20200501_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='restreamconfig',
            name='format',
            field=models.CharField(choices=[('flv', 'flv (RTMP)'), ('mpegts', 'mpegts (SRT)')], default='flv', help_text='restreamconfig_format_help', max_length=6),
        ),
    ]
